#!/bin/sh
#
# SYNOPSIS
#     Client-side MDM script to deploy Cove | Backup Manager with pre-generated private key credentials
#
# DESCRIPTION
#     CLIENT-SIDE COMPONENT — requires a server-side script to pre-generate devices with private key
#     encryption before this script is deployed via MDM.
#
#     Downloads the generic macOS Backup Manager installer and pre-creates config.ini
#     with Device/Account name, InstallationKey, and EncryptionKey. Supports force uninstallation of prior versions.
#
# USAGE
#     ./Deploy-Cove-Mac-PrivateKey.v03.sh -u <device_name> -p <installation_key> -k <encryption_key> [-d <download_path>] [-f]
#
# OPTIONS
#     -u, --user <device_name>     Mandatory: Device or Account name - lowercase, alphanumeric, hyphens, underscores (from Cove console)
#     -p, --password <inst_key>    Mandatory: InstallationKey - 12 alphanumeric characters (from Cove console)
#     -k, --key <encryption_key>   Mandatory: encryption key (8+ chars: digit, upper, lower, special [@#$%*?!;])
#     -d, --download <path>        Optional: download directory (default: /tmp)
#     -f, --force                  Optional: force uninstallation of prior version
#     -h, --help                   Show this help message
#
# EXAMPLES
#     ./Deploy-Cove-Mac-PrivateKey.v03.sh -u "device-001" -p "74dc06c4fce2" -k ";%c$GPgA4Ep05j?6"
#     ./Deploy-Cove-Mac-PrivateKey.v03.sh -u "device-001" -p "74dc06c4fce2" -k "P@ssw0rd!1234" -f
#     ./Deploy-Cove-Mac-PrivateKey.v03.sh -u "sample01" -p "74dc06c4fce2" -k ";%c$GPgA4Ep05j?6"
#     - Ensure that the script is run with sufficient privileges (sudo) for installation and service management.
#
# NOTES
#     - CLIENT-SIDE ONLY: device credentials must be pre-generated by the server-side script before MDM deployment.
#     - This script requires sudo for service management and installation.
#     - config.ini is created BEFORE installation with User, Password, and EncryptionKey
#     - After installation, it verifies if the BackupFP service is loaded and process is active.
#
# LEGAL
#     Sample scripts are not supported under any N-able support program or service.
#     The sample scripts are provided AS IS without warranty of any kind.
#     N-able expressly disclaims all implied warranties including, warranties
#     of merchantability or of fitness for a particular purpose.
#     In no event shall N-able or any other party be liable for damages arising
#     out of the use of or inability to use the sample scripts.
#
# COMPATIBILITY
#     For use with the Standalone edition of N-able | Cove Data Protection on macOS
#     Tested with Backup Manager 26.6
#

# Default values
DOWNLOAD_PATH="/tmp"
FORCE_UNINSTALL=0
USER=""
PASSWORD=""
ENCRYPTION_KEY=""
START_TIME=$(date +%s)
EXIT_CODE=0

# Logging functions
log_info() {
    echo "[INFO] $@"
}

log_warn() {
    echo "[WARN] $@" >&2
}

log_error() {
    echo "[ERROR] $@" >&2
}

log_success() {
    echo "[SUCCESS] $@"
}

# Print usage
usage() {
    cat << 'USAGE_END'
Usage: ./Deploy-Cove-Mac-PrivateKey.v03.sh -u <device_name> -p <installation_key> -k <encryption_key> [options]

Mandatory:
  -u, --user <device_name>      Device or Account name - lowercase, alphanumeric, hyphens, underscores (from Cove console)
  -p, --password <inst_key>     InstallationKey - 12 alphanumeric characters (from Cove console)
  -k, --key <encryption_key>    Encryption key (8+ chars: digit, upper, lower, special [@#$%*?!;])

Optional:
  -d, --download <path>         Download directory (default: /tmp)
  -f, --force                   Force uninstallation of prior version
  -h, --help                    Show this help message

Examples:
  ./Deploy-Cove-Mac-PrivateKey.v03.sh -u "device-001" -p "74dc06c4fce2" -k "P@ssw0rd!1234"
  ./Deploy-Cove-Mac-PrivateKey.v03.sh -u "device-001" -p "74dc06c4fce2" -k "P@ssw0rd!1234" -f
USAGE_END
    exit 1
}

# Parse arguments
while [ $# -gt 0 ]; do
    case "$1" in
        -u|--user)
            USER="$2"
            shift 2
            ;;
        -p|--password)
            PASSWORD="$2"
            shift 2
            ;;
        -k|--key)
            ENCRYPTION_KEY="$2"
            shift 2
            ;;
        -d|--download)
            DOWNLOAD_PATH="$2"
            shift 2
            ;;
        -f|--force)
            FORCE_UNINSTALL=1
            shift
            ;;
        -h|--help)
            usage
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            ;;
    esac
done

# Validate required parameters
if [ -z "$USER" ] || [ -z "$PASSWORD" ] || [ -z "$ENCRYPTION_KEY" ]; then
    log_error "Device name, InstallationKey, and encryption key are mandatory."
    usage
fi

log_info "Validating device name, InstallationKey, and encryption key..."

# Validate InstallationKey (12 alphanumeric characters)
KEY_LEN=$(echo "$PASSWORD" | wc -c)
if [ "$KEY_LEN" -ne 13 ]; then
    log_error "InstallationKey must be exactly 12 characters long (length: $((KEY_LEN - 1)))."
    exit 1
fi

if ! echo "$PASSWORD" | grep -qE '^[a-zA-Z0-9]{12}$'; then
    log_error "InstallationKey must contain only alphanumeric characters (a-z, A-Z, 0-9)."
    exit 1
fi

log_success "InstallationKey format is valid."

# Validate device name (lowercase, alphanumeric, hyphens, underscores only)
if ! echo "$USER" | grep -qE '^[a-z0-9_-]+$'; then
    log_error "Device name must contain only lowercase letters, numbers, hyphens, and underscores (no spaces or special characters)."
    exit 1
fi

log_success "Device name format is valid."

# Validate encryption key (8+ chars with digit, upper, lower, special)
KEY_LEN=$(echo "$ENCRYPTION_KEY" | wc -c)
if [ "$KEY_LEN" -lt 9 ]; then
    log_error "Encryption key must be at least 8 characters long."
    exit 1
fi

if ! echo "$ENCRYPTION_KEY" | grep -qE '[0-9]'; then
    log_error "Encryption key must contain at least one digit."
    exit 1
fi

if ! echo "$ENCRYPTION_KEY" | grep -qE '[A-Z]'; then
    log_error "Encryption key must contain at least one uppercase letter."
    exit 1
fi

if ! echo "$ENCRYPTION_KEY" | grep -qE '[a-z]'; then
    log_error "Encryption key must contain at least one lowercase letter."
    exit 1
fi

if ! echo "$ENCRYPTION_KEY" | grep -qE '[@#$%*?!;]'; then
    log_error "Encryption key must contain at least one special character from: @#\$%*?!;"
    exit 1
fi

log_success "Device name, InstallationKey, and encryption key validation passed."

# Check if Backup Manager is already installed
if [ "$FORCE_UNINSTALL" -ne 1 ] && [ -d "/Applications/Backup Manager.app" ]; then
    log_warn "Prior Backup Manager installation present, use -f flag to uninstall prior version."
    exit 1
fi

# Create download path directory if it does not exist
if [ ! -d "$DOWNLOAD_PATH" ]; then
    mkdir -p "$DOWNLOAD_PATH"
    log_info "Download path created: $DOWNLOAD_PATH"
fi

INSTALL_PATH="$DOWNLOAD_PATH/mxb-macosx-multiarch.pkg"

# Download the generic installation package
log_info "Downloading Backup Manager installer..."
if ! curl -f -L -o "$INSTALL_PATH" "https://cdn.cloudbackup.management/maxdownloads/mxb-macosx-multiarch.pkg"; then
    log_error "Failed to download installation package."
    exit 1
fi
log_success "Installation package downloaded successfully."

# If force flag is used and Backup Manager is installed, uninstall it
if [ "$FORCE_UNINSTALL" -eq 1 ] && [ -d "/Applications/Backup Manager.app" ]; then
    log_info "Force flag detected. Proceeding with uninstallation of prior Backup Manager..."
    
    # Stop the BackupFP service
    sudo launchctl unload -w /Library/LaunchDaemons/com.cloudbackup.BackupFP.plist 2>/dev/null || true
    
    # Remove the application
    sudo rm -rf "/Applications/Backup Manager.app"
    log_info "Removed application bundle."
    
    # Remove support and config files
    sudo rm -rf "/Library/Application Support/MXB/Backup Manager"
    log_info "Removed support and config files."
    
    # Remove log files
    sudo rm -rf "/Library/Logs/MXB/Backup Manager"
    log_info "Removed log files."
    
    # Remove the launchd plist
    sudo rm -f /Library/LaunchDaemons/com.cloudbackup.BackupFP.plist
    log_info "Removed launchd plist."
    
    log_success "Prior Backup Manager uninstalled."
fi

# Create config.ini with Device name, InstallationKey, and EncryptionKey
log_info "Creating configuration file with device credentials..."

CONFIG_DIR="/Library/Application Support/MXB/Backup Manager"
CONFIG_FILE="$CONFIG_DIR/config.ini"

# Create directory if it doesn't exist
sudo mkdir -p "$CONFIG_DIR"

# Create config.ini with all three fields
sudo tee "$CONFIG_FILE" > /dev/null << EOF
[General]
User=$USER
Password=$PASSWORD
EncryptionKey=$ENCRYPTION_KEY
EOF

log_success "Configuration file created with device name, InstallationKey, and encryption key."

# Install the Backup Manager
log_info "Installing Backup Manager..."
if ! sudo installer -pkg "$INSTALL_PATH" -target /; then
    log_error "Failed to install Backup Manager."
    rm -f "$INSTALL_PATH"
    exit 1
fi

log_success "Backup Manager installed successfully."
sleep 15

# Check if the BackupFP service is loaded and process is active
SERVICE_LOADED=0
PROCESS_RUNNING=0

# Check if BackupFP service is loaded
if sudo launchctl list | grep -q "com.cloudbackup.BackupFP"; then
    SERVICE_LOADED=1
fi

# Check if BackupFP process is running
if pgrep -q "BackupFP"; then
    PROCESS_RUNNING=1
fi

if [ "$SERVICE_LOADED" -eq 1 ] && [ "$PROCESS_RUNNING" -eq 1 ]; then
    log_success "BackupFP service is loaded and BackupFP process is active."
    EXIT_CODE=0
else
    log_warn "BackupFP service or process is not running as expected."
    EXIT_CODE=1
    
    # Retrieve the last error entry from the log file
    LOG_DIR="/Library/Logs/MXB/Backup Manager/BackupFP"
    if [ -d "$LOG_DIR" ]; then
        LATEST_LOG=$(ls -t "$LOG_DIR"/*.log 2>/dev/null | head -1)
        if [ -n "$LATEST_LOG" ] && [ -f "$LATEST_LOG" ]; then
            log_warn "Last error lines from log file:"
            grep '\[E\]' "$LATEST_LOG" 2>/dev/null | tail -5 | while read -r line; do
                log_warn "$line"
            done
        fi
    else
        log_info "Log directory not yet created: $LOG_DIR"
    fi
fi

# Clean up downloaded package
rm -f "$INSTALL_PATH"

# Calculate script duration
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))
log_info "Script run duration: ${DURATION}s"

exit $EXIT_CODE
